import User from '@/models/User';
import World from '@/models/World';
import League from '@/models/League';
import Team from '@/models/Team';
import Player from '@/models/Player';
import Match from "@/models/Match";
import Born from "@/models/Born";
import College from "@/models/College";
import Draft from "@/models/Draft";
import Ratings from "@/models/Ratings";
import Health from "@/models/Health";
import Injury from "@/models/Injury";
import Relative from "@/models/Relative";
import Salary from "@/models/Salary";
import Stat from "@/models/Stat";
import Transaction from "@/models/Transaction";
import Award from "@/models/Award";
import Overalls from "@/models/Overalls";
import Potentials from "@/models/Potentials";
import Skill from "@/models/Skill";
import Phase from "@/models/Phase";
import Contract from "@/models/Contract";
import TrainingSchedule from "@/models/TrainingSchedule";
import Activity from "@/models/Activity";
import Conference from "@/models/Conference";
import Division from "@/models/Division";
import Season from "@/models/Season";
import Staff from "@/models/Staff";

export interface RequestData {
    user: User[];
    world: World[];
    leagues: League[];
    teams: Team[];
    players: Player[];
    matches: Match[];
    born: Born[];
    college: College[];
    contracts: Contract[];
    draft: Draft[];
    ratings: Ratings[];
    health: Health[];
    salaries: Salary[];
    overalls: Overalls[];
    potentials: Potentials[];
    skills: Skill[];
    phases: Phase[];
    training_schedules: TrainingSchedule[];
    activities: Activity[];
    conference: Conference[];
    division: Division[];
    Season: Season[];
    staff: Staff[];
    awards: Award[];
    transactions: Transaction[];
    injuries: Injury[];
    relatives: Relative[];
    salary: Salary[];
    stat: Stat[];
    transaction: Transaction[];
}